### ISSUE TITLE
Unable to build docker image on arm64...

### ISSUE THREAD

**Issue by pppaapp** [Tsuk1ko/heroku-pximg-proxy#10]

**Comment by Tsuk1ko** [comment]
It works with linux arm64

https://github.com/Tsuk1ko/pximg-proxy/actions/runs/7788570503/job/21238255574

**Comment by pppaapp** [comment]
> It works with linux arm64
> 
> https://github.com/Tsuk1ko/pximg-proxy/actions/runs/7788570503/job/21238255574

Sorry, I misspoke

I can build a Docker image, but it won't run

x86 doesn't have this problem

**Comment by pppaapp** [comment]
I solved it by changing the dockerfile

```
FROM node:21

WORKDIR /app

COPY . .

RUN npm install -g ts-node

RUN mv ./docker/* ./

RUN npm install
RUN npm cache clean --force
RUN chmod -R 777 /app

CMD ["ts-node", "src/index.ts"]
```
