### ISSUE TITLE
通过 {pid}_{p} 爬取时只会获取 {pid}_p0

### ISSUE THREAD

**Issue by Lancercmd** [Tsuk1ko/heroku-pximg-proxy#2]
在正确部署的情况下，通过 {pid}_{p} 获取任意的多页作品时只会获取 {pid}_p0

而通过 {pid}/{p} 则正常，同时也确认了现版本的 i.loli.best 存在相同的问题

**Comment by Tsuk1ko** [comment]
请不要想当然地增加使用方法哈，使用方法可没说支持 https://i.loli.best/12345678_x 这种调用方式，请一律使用 https://i.loli.best/12345678/x

**Comment by Lancercmd** [comment]
。。哎，确实是没有的！
