### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Ruriko** [Tsuk1ko/heroku-pximg-proxy#4]
Can you add caching to your script? cause it'll greatly help reduce the amount of requests it makes to pixiv & bandwidth usage especially when you receive heavy traffic

**Comment by Tsuk1ko** [comment]
You can use nginx `proxy_cache` to handle caching.

For me, I use cloudflare to cache.

![image](https://user-images.githubusercontent.com/24877906/120731254-d0067000-c515-11eb-850f-a14161c0e34f.png)

**Comment by Tsuk1ko** [comment]
I don’t want to add cache handling to this script, which will make script more complex.

There are many ways to handle caching externally, and they are also better than I can handle.
